name: Build Flatpak
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  workflow_dispatch:
  workflow_call:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: fedora:43
      options: --privileged
    steps:
      - name: Install Flatpak dependencies
        run: |
          dnf update -y
          dnf install -y flatpak flatpak-builder xorg-x11-server-Xvfb git nodejs
          git config --global --add safe.directory '*'
          flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: flexa.flatpak
          manifest-path: io.github.eucaue.flexa.json
          cache-key: flatpak-${{ github.sha }}
          branch: master
          cache: ${{ !env.ACT }}
          upload-artifact: ${{ !env.ACT }}
      - name: Upload Flatpak artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: flexa-flatpak
          path: flexa.flatpak
