name: Test Windows Build
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-python
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-python-gobject
            mingw-w64-x86_64-libadwaita
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-glib2
            zip
      - name: Install PyInstaller and dependencies
        run: pip install pyinstaller win2xcur
      - name: Compile GSettings Schema
        run: glib-compile-schemas data/
      - name: Build with PyInstaller
        run: |
          mkdir -p package/share/icons
          cp -r /mingw64/share/icons/Adwaita package/share/icons/
          mkdir -p package/share/glib-2.0/schemas
          cp data/gschemas.compiled package/share/glib-2.0/schemas/
          pyinstaller --noconfirm --onedir --windowed \
            --add-data "src/window.ui;src" \
            --add-data "src/preferences-dialog.ui;src" \
            --add-data "src/shortcuts-dialog.ui;src" \
            --add-data "data/io.github.eucaue.flexa.gschema.xml;data" \
            src/main.py
          cp -r package/share dist/main/
      - name: Zip Release
        run: |
          cd dist
          zip -r flexa-windows.zip main/
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: flexa-windows
          path: dist/flexa-windows.zip
